# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: probedock-ruby 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "probedock-ruby"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Simon Oulevay (Alpha Hydrae)"]
  s.date = "2016-06-10"
  s.description = "Ruby library to develop new probes for Probe Dock. It can parse Probe Dock configuration files, collect test results and publish them to a Probe Dock server."
  s.email = "devops@probedock.io"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/probe_dock_ruby.rb",
    "lib/probe_dock_ruby/annotation.rb",
    "lib/probe_dock_ruby/client.rb",
    "lib/probe_dock_ruby/config.rb",
    "lib/probe_dock_ruby/project.rb",
    "lib/probe_dock_ruby/server.rb",
    "lib/probe_dock_ruby/tasks.rb",
    "lib/probe_dock_ruby/test_result.rb",
    "lib/probe_dock_ruby/test_run.rb",
    "lib/probe_dock_ruby/uid.rb",
    "lib/probedock-ruby.rb"
  ]
  s.homepage = "https://github.com/probedock/probedock-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Ruby library to develop new probes for Probe Dock."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oj>, ["~> 2.1"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.13"])
      s.add_runtime_dependency(%q<paint>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rake>, ["< 12.0", ">= 10.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rake-version>, ["~> 1.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_development_dependency(%q<fakefs>, ["~> 0.6"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<rspec-its>, ["~> 1.2"])
      s.add_development_dependency(%q<rspec-collection_matchers>, ["~> 1.1"])
      s.add_development_dependency(%q<coveralls>, ["~> 0.8"])
    else
      s.add_dependency(%q<oj>, ["~> 2.1"])
      s.add_dependency(%q<httparty>, ["~> 0.13"])
      s.add_dependency(%q<paint>, ["~> 1.0"])
      s.add_dependency(%q<rake>, ["< 12.0", ">= 10.1"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rake-version>, ["~> 1.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_dependency(%q<fakefs>, ["~> 0.6"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<rspec-its>, ["~> 1.2"])
      s.add_dependency(%q<rspec-collection_matchers>, ["~> 1.1"])
      s.add_dependency(%q<coveralls>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<oj>, ["~> 2.1"])
    s.add_dependency(%q<httparty>, ["~> 0.13"])
    s.add_dependency(%q<paint>, ["~> 1.0"])
    s.add_dependency(%q<rake>, ["< 12.0", ">= 10.1"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rake-version>, ["~> 1.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.10"])
    s.add_dependency(%q<fakefs>, ["~> 0.6"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<rspec-its>, ["~> 1.2"])
    s.add_dependency(%q<rspec-collection_matchers>, ["~> 1.1"])
    s.add_dependency(%q<coveralls>, ["~> 0.8"])
  end
end

